language: node_js
node_js:
  - "16.14.0"

version: ~> 1.0

cache: yarn

dist: focal

git:
    depth: 3
    quiet: true

before_install:
  - echo "Realizando meu primeiro teste"

jobs:
  fast_finish: true
  allow_failures:
    - name: "Test 2"
      if: branch != production
  include:
    - script: echo "Running my first travis project ...(1)"
    - stage: " My Project Build"
      name: "Tests"
      script:
        - echo "Testing my first project....(2)"
        - yarn run lint
        - yarn run test
    - stage: "My Project deploy"
        name: "DEV"
        if: branch = main
        script:
          - echo "Running deploy...(3)
          - ECHO $FIRST_ENV
        deploy:
          app: travis-study
            # main: app-travis-dev
            # production: app-travis-prod

